language: c
cache: ccache
matrix:
  - compiler: gcc
    env: CC=gcc
         CXX=g++
  - compiler: clang
    env: CC=clang
         CXX=clang++
env:
  MAKE="make -j2"
install:
  - sudo apt-get install libgmp-dev libmpfr-dev valgrind
  # set local directory and check name resolution
  - mkdir local
  - export PREFIX="/usr/local"
  - export LD_LIBRARY_PATH=${PREFIX}/lib:$LD_LIBRARY_PATH
  # build flint
  - wget http://flintlib.org/flint-2.5.2.tar.gz
  - tar xf flint-2.5.2.tar.gz
  - cd flint-2.5.2
  - ./configure --prefix=${PREFIX} && make && sudo make install
  - cd ..
  # build arb
  - wget https://github.com/fredrik-johansson/arb/archive/2.16.0.tar.gz
  - tar xf 2.16.0.tar.gz
  - cd arb-2.16.0
  - ./configure --prefix=${PREFIX} --with-flint=${PREFIX} && make && sudo make install
  - cd ..
  # check linking of installation
  - ldd ${PREFIX}/lib/libflint.so
  - ldd ${PREFIX}/lib/libarb.so
  # build e-antic
  - ./bootstrap.sh
  - ./configure CFLAGS="-I${PREFIX}/include" CPPFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib" --enable-valgrind
  - cat config.log
  - make
  - ldd .libs/libeantic.so

script:
  - V=1 make check VERBOSE=1
  - V=1 make check-valgrind VERBOSE=1
  - V=1 make distcheck DISTCHECK_CONFIGURE_FLAGS="CFLAGS=\"-I${PREFIX}/include\" CPPFLAGS=\"-I${PREFIX}/include\" LDFLAGS=\"-L${PREFIX}/lib\""
