language: python
env:
  - ""
  - CONFIGURE=--without-pthread
  - _CC=clang _CXX=clang++ _CPP=clang-cpp PACKAGES=clangxx
services:
  - docker
install:
  - sudo apt update
  - sudo apt install -y libc6-dbg
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n e-antic-build -c conda-forge python=$TRAVIS_PYTHON_VERSION antic libflint arb valgrind autoconf automake cxx-compiler c-compiler libtool boost-cpp $PACKAGES
  - conda activate e-antic-build
  - export CC=${_CC:-$CC}
  - export CXX=${_CXX:-$CXX}
  - export CPP=${_CPP:-$CPP}
script:
  - set -e
  - ./bootstrap.sh
  - ./configure --prefix=$CONDA_PREFIX --enable-valgrind ${CONFIGURE} || (cat config.log; false)
  - make
  - ldd .libs/libeantic.so
  - make check || (cat `find test-suite.log` /dev/null; false)
  - make check-valgrind || (cat `find test-suite-memcheck.log` /dev/null; false)
  - make distcheck
