language: c
cache: ccache
compiler:
  - gcc
  - clang
env:
  - MAKE="make -j2"
install:
  - sudo apt-get install libgmp-dev libmpfr-dev
  - mkdir local
  # build flint
  - git clone https://github.com/wbhart/flint2.git
  - cd flint2
  - ./configure --prefix=../local & make install
  - cd ..
  # build arb
  - git clone https://github.com/fredrik-johansson/arb.git
  - cd arb
  - ./configure --prefix=../local --with-flint=../local & make install
  - cd ..
  # build antic
  - git clone https://github.com/wbhart/antic.git
  - cd antic
  - git checkout build_system
  - ./configure --prefix=../local --with-arb=../local --with-flint=../local & make install
  - cd ..
  # check linking of installation
  - ldd local/lib/libflint.so
  - ldd local/lib/libfarb.so
  - ldd local/antic/lbantic.so
  # build e-antic
  - ./bootstrap.sh
  - ./configure --with-flint=local
  - make V=1

script:
  - make check V=1
