language: c
cache: ccache
compiler:
  - gcc
  - clang
env:
  - MAKE="make -j2"
  - CFLAGS="-I/$(realpath local/include)"
  - CPPFLAGS="-I$(realpath local/include)"
  - LDFLAGS="-L/$(realpath local/lib)"
install:
  - sudo apt-get install libgmp-dev libmpfr-dev
  - mkdir local
  # build flint
  - git clone https://github.com/wbhart/flint2.git
  - cd flint2
  - ./configure --prefix=../local && make install
  - cd ..
  # build arb
  - git clone https://github.com/fredrik-johansson/arb.git
  - cd arb
  - ./configure --prefix=../local --with-flint=../local && make install
  - cd ..
  # build antic
  - git clone https://github.com/wbhart/antic.git
  - cd antic
  - ./configure --prefix=../local --with-flint=../local && make install
  - cd ..
  # check linking of installation
  - ldd local/lib/libflint.so
  - ldd local/lib/libarb.so
  - ldd local/lib/libantic.so
  # build e-antic
  - ./bootstrap.sh
  - ./configure

script:
  - V=1 make distcheck
